# Generated by Django 4.2.3 on 2023-08-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='direction_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='direction_step',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
