# Generated by Django 4.2.3 on 2023-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_post_direction_body_post_direction_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='direction_step_number',
            field=models.IntegerField(default=0),
        ),
    ]
