# Generated by Django 4.2.3 on 2023-08-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_post_direction_step_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='direction_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='direction_step_number',
        ),
    ]
